// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fahvcbjynnhfydorkepr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhaHZjYmp5bm5oZnlkb3JrZXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzc4MzAsImV4cCI6MjA3MTcxMzgzMH0.ebNvDxzvYPRM_Y9a1UQ_g_q8dlmscLPza9PglTy2m5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});